// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WatchWaterConsumption;

#nullable disable

namespace WatchWaterConsumption.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WatchWaterConsumption.Models.WaterConsumption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AverageMonthlyKL")
                        .HasColumnType("integer");

                    b.Property<string>("Coordinates")
                        .HasColumnType("text");

                    b.Property<string>("Fill")
                        .HasColumnType("text");

                    b.Property<string>("FillOpacity")
                        .HasColumnType("text");

                    b.Property<string>("Neighbourhood")
                        .HasColumnType("text");

                    b.Property<string>("Stroke")
                        .HasColumnType("text");

                    b.Property<string>("StrokeOpacity")
                        .HasColumnType("text");

                    b.Property<string>("StrokeWidth")
                        .HasColumnType("text");

                    b.Property<string>("SuburbGroup")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Consumptions");
                });
#pragma warning restore 612, 618
        }
    }
}
